export { Film } from './Film'
export { Person } from './Person'
export { Planet } from './Planet'
export { Specie } from './Specie'
export { Starship } from './Starship'
export { Vehicle } from './Vehicle'